### ISSUE TITLE
Flatpak version cannot load Picture directory

### ISSUE THREAD

**Issue by dtantono** [flathub/com.xnview.XnViewMP#21]
Hi
I tested .deb file and flatpak version. But, this flatpak version cannot detect pictures directory on external NTFS partition. Is it a bug?

**Comment by joshas** [comment]
File system access was limited in following commit: https://github.com/flathub/com.xnview.XnViewMP/commit/417a6b79babdaed2e8c3bbda66627c9600b21d0d . I don't know true intentions for this change, but they might have been related to main Flatpak goals of [limiting application access to host environment](https://docs.flatpak.org/en/latest/sandbox-permissions.html).  

Considering that `host` option does not actually provide complete access to the host filesystem, but allows access to `/run/media`, where external devices are mounted, reverting that commit could be considered to improve user experience. As an alternative, adding `/run/media` and `media` directories to existing filesystem permissions, thus preventing application access to unnecessary system directories, could be even better solution.

I've created a fix and pull request with second option, but I would be interested to hear what more experienced Flatpak developers think about this solution, maybe there's even better way to fix this issue?

As a temporary workaround you can use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) to change permissions for installed Flatpak applications, including whitelisting custom directories, like `media` for external devices.

**Comment by joshas** [comment]
File system access was limited in following commit: https://github.com/flathub/com.xnview.XnViewMP/commit/417a6b79babdaed2e8c3bbda66627c9600b21d0d . I don't know true intentions for this change, but they might have been related to main Flatpak goals of [limiting application access to host environment](https://docs.flatpak.org/en/latest/sandbox-permissions.html).  

Considering that `host` option does not actually provide complete access to the host filesystem, but allows access to `/run/media`, where external devices are mounted, reverting that commit could be considered to improve user experience. As an alternative, adding `/run/media` and `media` directories to existing filesystem permissions, thus preventing application access to unnecessary system directories, could be even better solution.

I've created a fix and pull request with second option, but I would be interested to hear what more experienced Flatpak developers think about this solution, maybe there's even better way to fix this issue?

As a temporary workaround you can use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) to change permissions for installed Flatpak applications, including whitelisting custom directories, like `media` for external devices.
