### ISSUE TITLE
Build instructions ?

### ISSUE THREAD

**Issue by ScarFez** [flathub/com.xnview.XnViewMP#30]
Any hints/clues as to how to build ?

Appreciated, thanks

**Comment by gombosg** [comment]
Hey, IIRC we use `flatpak-builder` locally like `flatpak-builder build/ ./com.xnview.XnViewMP.yaml --user --force-clean --install`. Also, Flathub builds PR branches for us. :)

**Comment by ScarFez** [comment]
Any chance of building it not using flatpak ?

**Comment by gombosg** [comment]
This is the Flatpak repo. [XNViewMP](https://www.xnview.com/en/xnviewmp/) is AFAIK not open source, only freeware. This repo is only packaging config for flatpak.
