### ISSUE TITLE
Can't write files on Linux Mint 21

### ISSUE THREAD

**Issue by mat-m** [flathub/com.xnview.XnViewMP#33]
Hello

Version 1.4.4
I added GPS coords to a picture and tried to write it from xnviewMP through flatpak. I never could write the file, which consists in backuping the original and writing the modified version.
It works with the debian package.

I don't know which command I can run to help with the issue.

**Comment by joshas** [comment]
Could you describe how are you adding GPS coordinates to picture? What format original picture is in? Is picture in question stored in your "home" directory, or external drive?

**Comment by gombosg** [comment]
I can reproduce the issue. Pretty sure it's some sandboxing issue (like using some different file save method for GPS data), but without source code access it's hard to tell. Can't see anything special in logs either. The flatpak already has filesystem access.

You could try reporting the bug in the XnViewMP forums @mat-m , maybe they'll take a look.

**Comment by gombosg** [comment]
Closed due to inactivity.
