### ISSUE TITLE
Request: new version: 1.5.5 - 2023-09-08

### ISSUE THREAD

**Issue by zWhdmB5T** [flathub/com.xnview.XnViewMP#38]
# Request: new version: 1.5.5 - 2023-09-08
* [Changelog](https://www.xnview.com/en/xnviewmp/#changelog)
(this also includes v.1.5.4 with lots of changes and improvements!)

**Comment by gombosg** [comment]
Done in https://github.com/flathub/com.xnview.XnViewMP/pull/39

Feel free to submit PRs similar to this one, so that they could get merged faster.

**Comment by zWhdmB5T** [comment]
@gombosg Thank you!

About PRs for upcoming versions/releases: is a plain PR OK for you? Some projects require somehow detailed info…

**Comment by gombosg** [comment]
@zWhdmB5T Absolutely, these release bump PRs are trivial. 🙌🏽
