### ISSUE TITLE
Update XnViewMP to 0.94.2

### ISSUE THREAD

**Issue by joshas** [flathub/com.xnview.XnViewMP#5]
https://newsgroup.xnview.com/viewtopic.php?f=82&t=39812

**Comment by scx** [comment]
Currently, I am working on improving OCRFeeder. It should take about two days.
After that, I'll deal with XnView/XnConvert/XnRetro/XnSketch.

**Comment by scx** [comment]
**XnView  MP** `0.9.5` was released yesterday. As it introduces some important changes in libraries, I will first update this package to version `0.9.4.3`.

**Comment by DanMan** [comment]
No pressure but there've been a few updates in the meantime.

**Comment by gombosg** [comment]
Fixed by #9 #8
