### ISSUE TITLE
<pls delete>

### ISSUE THREAD

**Issue by BattouSaeen** [flathub/com.xnview.XnViewMP#65]
<irrelevant to flatpak d'oh>

**Comment by gombosg** [comment]
Hey, I think this is not a Flatpak packaging issue? Rather you could add a feature request to the XnView forums?

**Comment by BattouSaeen** [comment]
@gombosg ah haha I guess I messed up; I saw XnViewMP and didn't realise it was in the context of Flatpak. Sorry about that! Indeed I did post on the forums years ago but nothing came about, so I thought maybe that place is dead and github would have something :')
